services:
  postgres:
    image: postgres:17
    container_name: trueCode_currency_pgdb
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: TrueCode.CurrencyService.Migrator/Dockerfile
    depends_on:
      - postgres
    env_file: .env
    environment:
      - APPLY_MIGRATIONS=${APPLY_MIGRATIONS}
    restart: "no"

  userapi:
    build:
      context: .
      dockerfile: TrueCode.CurrencyService.UserApi/Dockerfile
    container_name: truecode_userapi
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "5161:5161"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

#  financeapi:
#    build:
#      context: .
#      dockerfile: TrueCode.CurrencyService.FinanceApi/Dockerfile
#    container_name: truecode_financeapi
#    depends_on:
#      - postgres
#    env_file: .env
#    ports:
#      - "5162:80"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
    
